### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stefanstoeckl** [leifdenby/namelist_python#3]
Hi @leifdenby , I just wanted to ask if there is any restriction on using/modifying/sharing the script.
I've started using it because it's simple and works well (Thanks for that!), but it's becoming more and more engrained into my model.
At some point I will share my code with some open source licence and therefore just wanted to ask how you feel about me including your code (with some minor cosmetic changes), obviously with full credits.

**Comment by leifdenby** [comment]
I'm very glad you found it useful. It is meant to be opensource too, so I'm completely happy for you to include it. I've added the GPL3 license just now. Hope that works for you :)

**Comment by stefanstoeckl** [comment]
Thank you very much for your reply, that's perfect.
