### ISSUE TITLE
Forward slashes in strings

### ISSUE THREAD

**Issue by joostadb** [leifdenby/namelist_python#7]
The following namelist file does not parse:

    &settings
    path = "/home/monkey/"
    /

because the forward slash in the string content of 'path' is parsed as the end of group &general. Therefore, the line

    path = "

is parsed and results in a NoSingleValueFoundException. The solution is to ignore string contents when separating groups in the line:

    group_re = re.compile(r'&([^&/]+)/', re.DOTALL)  # allow blocks to span multiple lines

Though I do not know how to do that exactly.

**Comment by leifdenby** [comment]
Thanks for this, I'll have a look
